version: "3.8" 

services:
  web:
    build: .
    container_name: web_service
    command: gunicorn app.wsgi:app --bind 0.0.0.0:8000
    ports:
      - "8000" 

  nginx:
    build: ./nginx
    container_name: nginx_service
    ports:
      - "8080:80"
